#This is a workflow to create a generic review in review tool test

name: Create ReviewTool Review

on:
  pull_request:
    types: [opened,reopened]  # Trigger when a new PR is opened or reopened
jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps as needed to build/test your code

      - name: Trigger ReviewTool URL
        run: |
          response=$(curl -s "https://rb-bbm-rtool-t2-fw-gway.apps.intranet.bosch.com/createReview/getTempReviewId/1")
          tempReviewId=$(echo "$response" | jq -r '.tempReviewId')
          # Make POST request with updated request body
          post_body=$(cat <<EOF
{
	"documentsList": [
		{
			"copyOfDocId": "",
			"docExtension": "LINK",
			"docId": "",
			"docNameWithoutTime": "${{ github.event.pull_request.html_url }}",
			"plDocSubTypeId": 267,
			"predSuccBean": {
				"predecessorDocNameWithoutTime": "",
				"predecessorDocNameWithTime": ""
			}
		}
	],
	"participantsList": [
		{
			"participantComments": "",
			"participantTypeId": 259,
			"participantUserId": 28372
		},
		{
			"participantComments": "",
			"participantTypeId": 260,
			"participantUserId": 4002
		}
	],
	"referenceLinkBeanList": [],
	"reviewDetailsBean": {
		"commonReviewDetail": {
			"buId": "1",
			"checkListIds": [
				306
			],
			"createdUserId": 28372,
			"createReviewMethodId": null,
			"interfaceId": "35",
			"isChklstCnfReq": "Y",
			"isWithoutWorkProduct": "N",
			"plId": "1",
			"reviewName": "TestGit",
			"reviewPlanEndDt": "2024-04-25",
			"reviewRemarks": null,
			"reviewTypeList": [
				{
					"reviewTypeVersionId": 584
				}
			],
			"tempReviewId": ${tempReviewId}
		},
		"prismDetails": {}
	}
}
EOF
)
    echo "POST Body: $post_body"

    # Make POST request to createReview
    curl -X POST -H "Content-Type: application/json" -d "$post_body" "https://rb-bbm-rtool-t2-fw-gway.apps.intranet.bosch.com/createReview/sw/generic/${tempReviewId}/1/1"
