# This is a workflow to create a generic review in review tool test
name: Create ReviewTool Review

on:
  pull_request:
    types: [opened, reopened]  # Trigger when a new PR is opened or reopened

jobs:
  Create_Review_RT:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps as needed to build/test your code

      - name: Trigger ReviewTool URL
        run: |
          response=$(curl -s "https://rb-bbm-rtool-t2-fw-gway.apps.intranet.bosch.com/createReview/getTempReviewId/1")
          tempReviewId=$(echo "$response" | jq -r '.tempReviewId')
          echo "Temp Review ID: $tempReviewId"
