name: Create Task List from PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-task-list:
    runs-on: ubuntu-latest
    
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine Task List Filename, Get File Contents, and Create Task List Comment
        run: |
          if [[ "$PR_TITLE" == *"task1"* ]]; then
            FILENAME="task_list_1.md"
          elif [[ "$PR_TITLE" == *"task2"* ]]; then
            FILENAME="task_list_2.md"
          else
            echo "No matching task list found for PR title"
            exit 1
          fi
          
          file_content=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/repos/${{ github.repository }}/contents/docs/${FILENAME}")
          ENCODED_CONTENT=$(echo "$file_content" | jq -r '.content')
          DECODED_CONTENT=$(echo "$ENCODED_CONTENT" | base64 --decode)
          
          echo "Decoded Content: $DECODED_CONTENT"

          # Create Task List Comment
          const github = require('@actions/github');
          const context = github.context;
          const octokit = new github.getOctokit(process.env.GITHUB_TOKEN);

          const comment = `
          ### Task List
          
          ${DECODED_CONTENT}
          `;

          await octokit.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: comment
          });
